server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: container_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      - json:
      - json:
          expressions:
            stream: stream
            container_name: attrs.container_name
            image_name: attrs.image_name
      - labels:
          stream:
          container_name:
          image_name: